version: "3.3"

services:
    scraper_srv:
        build: ./scraper_srv
        ports: 
            - "8081:8080"
        environment: 
            - URL_TO_SCRAP="https://meneame.net"
    postgres:
        image: 'postgres:latest'
        restart: always
        volumes:
            - './postgres_data:/var/lib/postgresql/data'
        environment:
            - POSTGRES_PASSWORD=arm001
        ports:
            - '5432:5432'