version: "3.3"

services:
    scraper_srv:
        build: ./scraper_srv
        ports: 
            - "8081:8080"
        environment: 
            - URL_TO_SCRAP2=https://www.xataka.com/
            - DB_HOST=mongodb
    mongodb:
        image : mongo
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - /mongodb/database:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped